// src/App.svelte
<script>
  import { onMount } from 'svelte';
  import Legend from './components/Legend.svelte';
  import HighlightedTextBox from './components/HighlightedTextBox.svelte';
  import FlashValue from './components/FlashValue.svelte';
  import CopyPromptButton from './components/CopyPromptButton.svelte';
  import ScoreTable from './components/ScoreTable.svelte';
  import { rollCopyPicks } from './lib/copyPools.js';
  import { evaluateGate } from './lib/gates.js';
  import {
    computeMetrics,
    formatCliGradePhrase,
    formatDaleGradePhrase,
    formatGunningFogPhrase,
    getDifficultWordChips,
    rs,
  } from './lib/readability.js';
  import { evaluatePasteSecurity } from './lib/security.js';
  import {
    SENTENCE_LENGTH_COLORS,
    analyzeSentenceLength,
    buildSentenceLengthSegments,
    hasLongSentenceHighlight,
  } from './lib/sentenceLength.js';
  import { tokenizeWithGaps } from './lib/tokenizer.js';
  import {
    POS_COLORS,
    REPEAT_HIGHLIGHT,
    analyzeWordVariety,
    buildPosHighlightSegments,
    buildRepeatHighlightSegments,
  } from './lib/wordVariety.js';
  import { buildImprovePrompt, gatherPromptInputs } from './lib/improvePrompt.js';
  import { DIFFICULT_WORD_HIGHLIGHT } from './lib/overlay.js';
  import { pickPlaceholder } from './lib/placeholders.js';
  import {
    formatScore,
    posHighlightColor,
    segmentStyle,
    sentenceHighlightColor,
    syllableClass,
    syllableHighlightColor,
    syllableTooltipLabel,
  } from './lib/highlightHelpers.js';
  import {
    ANALYSIS_DEBOUNCE_MS,
    BUTTON_STYLE,
    DALE_ROWS,
    FONT,
    FOOTER_ICON_LINK_STYLE,
    FOOTER_LINK_STYLE,
    FRE_ROWS,
    H1_STYLE,
    H2_STYLE,
    IN_TEXT_BOX_STYLE,
    LINK_STYLE,
    PAGE_STYLE,
    POS_BUCKETS,
    PROSE_STYLE,
    SECTION_GAP,
    SECTION_GAP_FIRST,
    STACK_PACKAGES,
    SYLLABLE_COLORS,
    TEXTAREA_STYLE,
  } from './lib/uiConstants.js';

  let { flashOnChange = false } = $props();

  let rawInput = $state('');
  let analysisText = $state('');
  let securityBlock = $state(null);
  let flashToggle = $state(0);
  const placeholder = pickPlaceholder();
  let syllableLegendHover = $state(null);
  let sentenceLegendHover = $state(null);
  let posLegendHover = $state(null);

  let pendingPaste = false;
  let prevMetrics = null;

  onMount(() => {
    window.scrollTo(0, 0);
  });

  function handleChange(event) {
    const value = event.currentTarget.value;

    if (!value.trim()) {
      rawInput = '';
      analysisText = '';
      securityBlock = null;
      pendingPaste = false;
      return;
    }

    if (pendingPaste) {
      pendingPaste = false;
      const security = evaluatePasteSecurity(value);

      if (!security.allowed) {
        securityBlock = security.reason;
        analysisText = '';
        rawInput = security.sanitized;
        return;
      }

      securityBlock = null;
      rawInput = security.sanitized;
      return;
    }

    securityBlock = null;
    rawInput = value;
  }

  $effect(() => {
    if (!rawInput.trim() || securityBlock) return;

    const timer = setTimeout(() => {
      analysisText = rawInput;
    }, ANALYSIS_DEBOUNCE_MS);

    return () => clearTimeout(timer);
  });

  function handlePaste() {
    pendingPaste = true;
  }

  function handleClear() {
    rawInput = '';
    analysisText = '';
    securityBlock = null;
    pendingPaste = false;
  }

  const gate = $derived(evaluateGate(analysisText));

  const metrics = $derived.by(() => {
    if (gate.type !== 'ok') return null;
    return computeMetrics(analysisText);
  });

  const wordVariety = $derived.by(() => {
    if (gate.type !== 'ok') return null;
    return analyzeWordVariety(analysisText);
  });

  const copy = $derived.by(() => {
    if (gate.type !== 'ok' || !metrics || !wordVariety) return null;
    return rollCopyPicks(metrics, wordVariety);
  });

  $effect(() => {
    if (!flashOnChange || !metrics || !prevMetrics) {
      prevMetrics = metrics;
      return;
    }
    const prev = prevMetrics;
    if (
      prev.flesch !== metrics.flesch ||
      prev.cli !== metrics.cli ||
      prev.gunningFog !== metrics.gunningFog ||
      prev.dale !== metrics.dale ||
      prev.difficultCount !== metrics.difficultCount
    ) {
      flashToggle += 1;
    }
    prevMetrics = metrics;
  });

  const skipHighlight = $derived(analysisText.length > 20000);

  const syllableSegments = $derived.by(() => {
    if (skipHighlight || gate.type !== 'ok') return null;
    return tokenizeWithGaps(analysisText).map((seg) => {
      if (seg.type === 'gap') return seg;
      const count = syllableClass(rs.syllableCount(seg.text));
      return { ...seg, syllables: count };
    });
  });

  const sentenceLengthStats = $derived.by(() => {
    if (gate.type !== 'ok') return null;
    return analyzeSentenceLength(analysisText);
  });

  const sentenceLengthSegments = $derived.by(() => {
    if (skipHighlight || gate.type !== 'ok') return null;
    return buildSentenceLengthSegments(analysisText);
  });

  const showSentenceLengthBox = $derived(
    sentenceLengthSegments && hasLongSentenceHighlight(sentenceLengthSegments),
  );

  const sentenceBandCounts = $derived.by(() => {
    const counts = { borderline: 0, 'too-long': 0 };
    if (!sentenceLengthStats) return counts;
    for (const sentence of sentenceLengthStats.sentences) {
      if (sentence.band === 'borderline') counts.borderline += 1;
      if (sentence.band === 'too-long') counts['too-long'] += 1;
    }
    return counts;
  });

  const hardWordSegments = $derived.by(() => {
    if (skipHighlight || gate.type !== 'ok' || !metrics) return null;
    return tokenizeWithGaps(analysisText).map((seg) => {
      if (seg.type === 'gap') return seg;
      const hard = metrics.difficultLookup.has(seg.text.toLowerCase());
      return { ...seg, hard };
    });
  });

  const chips = $derived.by(() => {
    if (!metrics || metrics.difficultCount === 0) return [];
    return getDifficultWordChips(analysisText, metrics.difficultWords);
  });

  const repeatSegments = $derived.by(() => {
    if (skipHighlight || gate.type !== 'ok' || !wordVariety) return null;
    if (wordVariety.repeated.words.length === 0) return null;
    return buildRepeatHighlightSegments(
      analysisText,
      wordVariety.repeated.surfaceLookup,
    );
  });

  const posSegments = $derived.by(() => {
    if (skipHighlight || gate.type !== 'ok') return null;
    return buildPosHighlightSegments(analysisText);
  });

  const improvePrompt = $derived.by(() => {
    if (gate.type !== 'ok' || !metrics || !wordVariety || !sentenceLengthStats) {
      return null;
    }
    const inputs = gatherPromptInputs(
      analysisText,
      metrics,
      sentenceLengthStats,
      wordVariety,
    );
    return buildImprovePrompt(inputs);
  });

  const showResults = $derived(
    !securityBlock && gate.type === 'ok' && metrics && copy,
  );
</script>

<div style={PAGE_STYLE}>
  <h1 style={H1_STYLE}>Text Readability</h1>

  <textarea
    value={rawInput}
    oninput={handleChange}
    onpaste={handlePaste}
    {placeholder}
    spellcheck="false"
    style={TEXTAREA_STYLE}
  ></textarea>

  {#if rawInput.trim() !== ''}
    <div style="margin-top:0.65rem;display:flex;flex-wrap:wrap;gap:0.5rem">
      <button type="button" onclick={handleClear} style={BUTTON_STYLE}>Clear</button>
    </div>
  {/if}

  {#if securityBlock && rawInput.trim() !== ''}
    <div
      style="margin-top:1.6rem;background:#fff6f5;border:1px solid #e6b9b4;border-left:4px solid #9a2b2b;border-radius:5px;padding:0.85rem 1rem"
    >
      <span style="color:#7a2222;font-size:0.9rem">
        {securityBlock === 'code'
          ? 'This looks like source code, not prose. Paste readable English text to get scores.'
          : 'This paste looks unsafe. Readability analysis only works with plain text, so remove scripts or markup and try again.'}
      </span>
    </div>
  {/if}

  {#if !securityBlock && gate.type === 'non-english' && analysisText.trim() !== ''}
    <div
      style="margin-top:1.6rem;background:#fff6f5;border:1px solid #e6b9b4;border-left:4px solid #9a2b2b;border-radius:5px;padding:0.85rem 1rem"
    >
      <span style="color:#7a2222;font-size:0.9rem">
        This text doesn't look like English. Readability scores are calculated for English text
        only. Paste English text to see the metrics.
      </span>
    </div>
  {/if}

  {#if !securityBlock && gate.type === 'too-short' && analysisText.trim() !== ''}
    <div
      style="margin-top:1.6rem;background:#f5f5f5;border:1px solid #d9d9d9;border-radius:5px;padding:0.85rem 1rem"
    >
      <span style="color:#3a3a3a;font-size:0.9rem">
        A little more text, please. Readability formulas need at least 12 words to say anything
        meaningful, so add about {12 - gate.wordCount} more.
      </span>
    </div>
  {/if}

  {#if showResults}
    <section style={SECTION_GAP_FIRST}>
      <h2 style={H2_STYLE}>Flesch Reading Ease</h2>
      <p style={PROSE_STYLE}>{copy.freIntro}</p>
      {#if syllableSegments}
        <Legend
          items={[
            { key: 2, label: '2 syllables', color: SYLLABLE_COLORS[2] },
            { key: 3, label: '3 syllables', color: SYLLABLE_COLORS[3] },
            { key: 4, label: '4+ syllables', color: SYLLABLE_COLORS[4] },
          ]}
          bind:activeKey={syllableLegendHover}
          interactive
        />
        <HighlightedTextBox
          segments={syllableSegments}
          getBackground={(seg) =>
            syllableHighlightColor(seg.syllables, syllableLegendHover)}
          getTooltip={(seg) => syllableTooltipLabel(seg.syllables)}
        />
      {/if}
      <p
        style="{PROSE_STYLE}{syllableSegments
          ? ';margin:0.9rem 0 0.9rem'
          : ''}"
      >
        Your score is
        <FlashValue
          value={formatScore(metrics.flesch)}
          {flashOnChange}
          {flashToggle}
        />, rated <span style="font-weight:700">{metrics.fleschBand.label.toLowerCase()}</span>.
        {copy.freReader}
      </p>
      <ScoreTable
        rows={FRE_ROWS}
        activeIndex={metrics.fleschBand.index}
        columns={['Score', 'Difficulty']}
      />
    </section>

    <section style={SECTION_GAP}>
      <h2 style={H2_STYLE}>Sentence length</h2>
      <p style={PROSE_STYLE}>
        {sentenceLengthStats && sentenceLengthStats.longCount > 0
          ? copy.sentenceLongLine(
              sentenceLengthStats.longCount,
              sentenceLengthStats.total,
            )
          : copy.sentenceOkLine}
      </p>
      {#if showSentenceLengthBox}
        <Legend
          items={[
            {
              key: 'borderline',
              label: '21 to 30 words',
              color: SENTENCE_LENGTH_COLORS.borderline,
              disabled: sentenceBandCounts.borderline === 0,
            },
            {
              key: 'too-long',
              label: '31+ words',
              color: SENTENCE_LENGTH_COLORS['too-long'],
              disabled: sentenceBandCounts['too-long'] === 0,
            },
          ]}
          bind:activeKey={sentenceLegendHover}
          interactive
        />
        <div style={IN_TEXT_BOX_STYLE}>
          {#each sentenceLengthSegments as seg, i (i)}
            {#if seg.type === 'gap'}
              <span style={segmentStyle()}>{seg.text}</span>
            {:else}
              <span
                style={segmentStyle(
                  sentenceHighlightColor(seg.band, sentenceLegendHover),
                )}>{seg.text}</span
              >
            {/if}
          {/each}
        </div>
      {/if}
      {#if sentenceLengthStats && sentenceLengthStats.total > 0}
        <p
          style="color:#555;font-size:0.9rem;margin:{showSentenceLengthBox
            ? '0.75rem 0 0'
            : '0'}"
        >
          Longest sentence: <span style="font-weight:700">{sentenceLengthStats.longest}</span>
          words.
        </p>
      {/if}
    </section>

    <section style={SECTION_GAP}>
      <h2 style={H2_STYLE}>Coleman–Liau Index</h2>
      <p style={PROSE_STYLE}>{copy.cliIntro}</p>
      <p style="{PROSE_STYLE};margin:0">
        The Coleman–Liau Index puts this text at
        <span style="font-weight:700"
          >{formatCliGradePhrase(metrics.cli, metrics.cliBucket)}</span
        >.
        {copy.cliReader}
      </p>
    </section>

    <section style={SECTION_GAP}>
      <h2 style={H2_STYLE}>Gunning Fog Index</h2>
      <p style={PROSE_STYLE}>{copy.gunningIntro}</p>
      <p style="{PROSE_STYLE};margin:0">
        The Gunning Fog Index puts this text at
        <span style="font-weight:700"
          >{formatGunningFogPhrase(metrics.gunningFog, metrics.gunningBucket)}</span
        >.
        {copy.gunningReader}
      </p>
    </section>

    <section style={SECTION_GAP}>
      <h2 style={H2_STYLE}>Dale–Chall Readability</h2>
      <p style={PROSE_STYLE}>{copy.daleIntro}</p>
      <p style={PROSE_STYLE}>
        Your
        <span style="font-weight:700"
          >{formatDaleGradePhrase(
            metrics.dale,
            metrics.daleBand.index,
            metrics.daleBand.label,
          )}</span
        >.
        {copy.daleReader}
      </p>
      <ScoreTable
        rows={DALE_ROWS}
        activeIndex={metrics.daleBand.index}
        columns={['Score', 'Reading level']}
      />
    </section>

    <section style={SECTION_GAP}>
      <h2 style={H2_STYLE}>Parts of speech mix</h2>
      <p style="{PROSE_STYLE};margin:0 0 0.75rem">{copy.posSummary}</p>
      <div
        style="display:flex;width:100%;height:0.75rem;border-radius:3px;overflow:hidden;margin-bottom:0.55rem"
      >
        {#each POS_BUCKETS as bucket}
          {@const pct = wordVariety.pos.percentages[bucket.key]}
          {#if pct > 0}
            <div style="width:{pct}%;background:{POS_COLORS[bucket.key]}"></div>
          {/if}
        {/each}
      </div>
      <Legend
        items={POS_BUCKETS.map((bucket) => ({
          key: bucket.key,
          label: `${bucket.label} ${wordVariety.pos.percentages[bucket.key]}%`,
          color: POS_COLORS[bucket.key],
        }))}
        bind:activeKey={posLegendHover}
        interactive
      />
      {#if posSegments}
        <HighlightedTextBox
          segments={posSegments}
          getBackground={(seg) => posHighlightColor(seg.pos, posLegendHover)}
          getTooltip={(seg) => seg.posLabel}
        />
      {/if}

      <h2 style="{H2_STYLE};margin-top:2.8rem">Repeated words</h2>
      <p style="{PROSE_STYLE};margin:0 0 0.75rem">{copy.repeatSummary}</p>
      {#if repeatSegments}
        <Legend items={[{ label: 'Repeated word', color: REPEAT_HIGHLIGHT }]} />
        <div style={IN_TEXT_BOX_STYLE}>
          {#each repeatSegments as seg, i (i)}
            {#if seg.type === 'gap'}
              <span style={segmentStyle()}>{seg.text}</span>
            {:else}
              <span
                style={segmentStyle(seg.repeat ? REPEAT_HIGHLIGHT : undefined)}
                >{seg.text}</span
              >
            {/if}
          {/each}
        </div>
      {/if}
      {#if wordVariety.repeated.words.length > 0}
        <div
          style="display:flex;flex-wrap:wrap;gap:0.5rem;margin-top:{repeatSegments
            ? '0.75rem'
            : '0'}"
        >
          {#each wordVariety.repeated.words as chip (chip.word)}
            <span
              style="padding:0.4rem 0.8rem;background:#f5f5f5;border:1px solid #d9d9d9;border-radius:999px;font-size:0.95rem;display:inline-flex;align-items:center;gap:0.45rem"
            >
              {chip.word}
              <span
                style="background:#e0e0e0;border-radius:999px;font-size:0.72rem;font-weight:700;color:#555;padding:0.1rem 0.4rem"
              >
                ×{chip.count}
              </span>
            </span>
          {/each}
        </div>
      {/if}

      <h2 style="{H2_STYLE};margin-top:2.8rem">Lexical density</h2>
      <p style="margin:0 0 0.5rem;color:#3a3a3a;font-size:1rem">
        <span style="font-weight:700">{wordVariety.lexicalDensity.percent}</span> percent
      </p>
      <p style="{PROSE_STYLE};margin:0">{copy.densityLine}</p>
    </section>

    <section style={SECTION_GAP}>
      <h2 style={H2_STYLE}>Difficult words</h2>
      <p style={PROSE_STYLE}>{copy.difficultIntro}</p>
      {#if metrics.difficultCount >= 1 && hardWordSegments}
        <Legend
          items={[{ label: 'Hard word', color: DIFFICULT_WORD_HIGHLIGHT }]}
        />
        <div style={IN_TEXT_BOX_STYLE}>
          {#each hardWordSegments as seg, i (i)}
            {#if seg.type === 'gap'}
              <span style={segmentStyle()}>{seg.text}</span>
            {:else}
              <span
                style={segmentStyle(seg.hard ? DIFFICULT_WORD_HIGHLIGHT : undefined)}
                >{seg.text}</span
              >
            {/if}
          {/each}
        </div>
      {/if}
      <p
        style="{PROSE_STYLE}{metrics.difficultCount >= 1 && hardWordSegments
          ? ';margin:0.9rem 0 0.8rem'
          : ''}"
      >
        {#if metrics.difficultCount > 0}
          <span style="font-weight:700">{metrics.difficultWords.length}</span> distinct words
          below account for <span style="font-weight:700">{metrics.difficultCount}</span> of your
          <span style="font-weight:700">{metrics.lexicon}</span> words (about
          <span style="font-weight:700"
            >{Math.round((metrics.difficultCount / metrics.lexicon) * 100)}%</span
          >). These are the longer, less familiar words the formulas count against you, so swapping
          them for simpler ones is the quickest way to lift every score above.
        {:else}
          Nothing stands out. Your text is built almost entirely from short, familiar words, which
          is exactly what keeps the scores easy.
        {/if}
      </p>
      {#if chips.length > 0}
        <div style="display:flex;flex-wrap:wrap;gap:0.5rem">
          {#each chips as chip (chip.word)}
            <span
              style="padding:0.4rem 0.8rem;background:#f5f5f5;border:1px solid #d9d9d9;border-radius:999px;font-size:0.95rem;display:inline-flex;align-items:center;gap:0.45rem"
            >
              {chip.word}
              {#if chip.count > 1}
                <span
                  style="background:#e0e0e0;border-radius:999px;font-size:0.72rem;font-weight:700;color:#555;padding:0.1rem 0.4rem"
                >
                  ×{chip.count}
                </span>
              {/if}
            </span>
          {/each}
        </div>
      {/if}
    </section>

    <section style={SECTION_GAP}>
      <h2 style={H2_STYLE}>Improve with AI</h2>
      <p style="color:#3a3a3a;font-size:1rem;margin:0 0 0.9rem">
        Copy this prompt into any LLM to get a clearer rewrite that keeps your original meaning.
      </p>
      <div
        style="border:1px solid #d9d9d9;border-radius:5px;padding:1rem 1.1rem;background:#f5f7ff;font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;font-size:0.9rem;line-height:1.5;white-space:pre-wrap;word-break:break-word;color:#212121;max-height:22rem;overflow:auto"
      >
        {improvePrompt}
      </div>
      <div style="margin-top:0.65rem">
        <CopyPromptButton text={improvePrompt} />
      </div>
    </section>

    <section style={SECTION_GAP}>
      <h2 style={H2_STYLE}>Built with</h2>
      <p style="font-family:{FONT};font-size:1rem;line-height:1.6;color:#3a3a3a;margin:0 0 0.9rem">
        These npm packages run in your browser. No uploads, no API calls, no API keys.
      </p>
      <div style="font-family:{FONT};font-size:1rem;line-height:1.75;color:#3a3a3a">
        {#each STACK_PACKAGES as item (item.name)}
          <div style="margin-bottom:0.65rem">
            <a
              href={item.href}
              target="_blank"
              rel="noopener noreferrer"
              style="{LINK_STYLE};font-weight:700"
            >
              {item.name}
            </a>
            <span>: {item.role}</span>
          </div>
        {/each}
      </div>
    </section>
  {/if}

  <footer style="margin-top:2.25rem;font-size:0.8rem;line-height:1.6;color:#888">
    <p
      style="margin:0;display:flex;flex-wrap:nowrap;align-items:center;gap:0.35rem;white-space:nowrap"
    >
      <span>Built by</span>
      <a
        href="https://www.sischreiber.com"
        target="_blank"
        rel="noopener noreferrer"
        style={FOOTER_LINK_STYLE}
      >
        sischreiber
      </a>
      <a
        href="https://github.com/sischreiber/text-readability"
        target="_blank"
        rel="noopener noreferrer"
        style={FOOTER_ICON_LINK_STYLE}
        aria-label="GitHub repository"
        title="GitHub"
      >
        <svg aria-hidden="true" width="14" height="14" viewBox="0 0 16 16" fill="currentColor">
          <path
            d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.013 8.013 0 0016 8c0-4.42-3.58-8-8-8z"
          />
        </svg>
      </a>
      <span>
        Readability scores from open source npm packages, running entirely in your browser.
      </span>
    </p>
  </footer>
</div>

// src/App.jsx
import { useEffect, useMemo, useRef, useState } from 'react';
import { rollCopyPicks } from './lib/copyPools';
import { evaluateGate } from './lib/gates';
import {
  STYLE_COLORS,
  buildCharOverlay,
  categorizeStyleHit,
  findDifficultWordPositions,
  mergeCharRuns,
} from './lib/overlay';
import {
  computeMetrics,
  getDifficultWordChips,
  rs,
} from './lib/readability';
import { tokenizeWithGaps } from './lib/tokenizer';
import {
  hasWriteGoodFailed,
  isWriteGoodLoaded,
  loadWriteGood,
  runWriteGood,
} from './lib/writeGoodLoader';

const FONT =
  "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif";

const SYLLABLE_COLORS = {
  2: '#e7eeff',
  3: '#c6d6ff',
  4: '#a4bcff',
};

const FRE_ROWS = [
  { range: '90–100', label: 'Very Easy', min: 90 },
  { range: '80–89', label: 'Easy', min: 80 },
  { range: '70–79', label: 'Fairly Easy', min: 70 },
  { range: '60–69', label: 'Standard', min: 60 },
  { range: '50–59', label: 'Fairly Difficult', min: 50 },
  { range: '30–49', label: 'Difficult', min: 30 },
  { range: '0–29', label: 'Very Confusing', min: 0 },
];

const DALE_ROWS = [
  { range: '4.9 or lower', label: 'Grade 4 and below', match: (s) => s <= 4.9 },
  { range: '5.0 to 5.9', label: 'Grades 5 to 6', match: (s) => s >= 5.0 && s <= 5.9 },
  { range: '6.0 to 6.9', label: 'Grades 7 to 8', match: (s) => s >= 6.0 && s <= 6.9 },
  { range: '7.0 to 7.9', label: 'Grades 9 to 10', match: (s) => s >= 7.0 && s <= 7.9 },
  { range: '8.0 to 8.9', label: 'Grades 11 to 12', match: (s) => s >= 8.0 && s <= 8.9 },
  { range: '9.0 to 9.9', label: 'College', match: (s) => s >= 9.0 && s <= 9.9 },
  { range: '10.0 and up', label: 'College graduate', match: (s) => s >= 10.0 },
];

const STYLE_LEGEND = [
  { label: 'Passive voice', color: STYLE_COLORS['Passive voice'] },
  { label: 'Weasel word', color: STYLE_COLORS['Weasel word'] },
  { label: 'Wordy', color: STYLE_COLORS.Wordy },
  { label: 'Adverb', color: STYLE_COLORS.Adverb },
  { label: 'Cliché', color: STYLE_COLORS['Cliché'] },
  { label: 'Hard word', color: STYLE_COLORS.Difficult },
];

function syllableClass(count) {
  if (count <= 1) return 1;
  if (count >= 4) return 4;
  return count;
}

function formatScore(value) {
  return (Math.round(value * 10) / 10).toFixed(1);
}

function Legend({ items }) {
  return (
    <div
      style={{
        display: 'flex',
        flexWrap: 'wrap',
        gap: '0.65rem 1rem',
        marginBottom: '0.55rem',
        fontSize: '0.8rem',
        color: '#555',
      }}
    >
      {items.map((item) => (
        <div key={item.label} style={{ display: 'flex', alignItems: 'center', gap: '0.4rem' }}>
          <span
            style={{
              width: '0.9rem',
              height: '0.9rem',
              borderRadius: '3px',
              border: '1px solid #d0d0d0',
              background: item.color ?? 'transparent',
              flexShrink: 0,
            }}
          />
          <span>{item.label}</span>
        </div>
      ))}
    </div>
  );
}

function InTextBox({ children }) {
  return (
    <div
      style={{
        whiteSpace: 'normal',
        wordBreak: 'break-word',
        fontSize: '1rem',
        lineHeight: 1.9,
        padding: '1rem 1.1rem',
        border: '1px solid #d9d9d9',
        borderRadius: '5px',
        color: '#212121',
      }}
    >
      {children}
    </div>
  );
}

function SegmentSpan({ text, background }) {
  return (
    <span
      style={{
        whiteSpace: 'pre-wrap',
        borderRadius: '3px',
        padding: '0.08em 0',
        background: background ?? 'transparent',
        color: '#212121',
      }}
    >
      {text}
    </span>
  );
}

function FlashValue({ value, flashOnChange, flashToggle }) {
  const prev = useRef(value);
  const [anim, setAnim] = useState(null);

  useEffect(() => {
    if (!flashOnChange || prev.current === value) {
      prev.current = value;
      return;
    }
    setAnim(flashToggle % 2 === 0 ? 'flashA' : 'flashB');
    prev.current = value;
    const timer = setTimeout(() => setAnim(null), 600);
    return () => clearTimeout(timer);
  }, [value, flashOnChange, flashToggle]);

  return (
    <span
      style={{
        fontVariantNumeric: 'tabular-nums',
        animation: anim ? `${anim} 0.6s ease` : undefined,
      }}
    >
      {value}
    </span>
  );
}

function ScoreTable({ rows, activeIndex, columns }) {
  return (
    <table
      style={{
        borderCollapse: 'collapse',
        fontSize: '1rem',
        width: '100%',
      }}
    >
      <thead>
        <tr>
          {columns.map((col) => (
            <th
              key={col}
              style={{
                border: '1px solid #d9d9d9',
                padding: '0.7rem 1.4rem 0.7rem 0.9rem',
                textAlign: 'left',
                fontWeight: 700,
              }}
            >
              {col}
            </th>
          ))}
        </tr>
      </thead>
      <tbody>
        {rows.map((row, index) => {
          const active = index === activeIndex;
          return (
            <tr key={row.label}>
              <td
                style={{
                  border: '1px solid #d9d9d9',
                  padding: '0.7rem 1.4rem 0.7rem 0.9rem',
                  background: active ? '#e9e9e9' : '#fff',
                  fontWeight: active ? 700 : 400,
                }}
              >
                {row.range}
              </td>
              <td
                style={{
                  border: '1px solid #d9d9d9',
                  padding: '0.7rem 1.4rem 0.7rem 0.9rem',
                  background: active ? '#e9e9e9' : '#fff',
                  fontWeight: active ? 700 : 400,
                }}
              >
                {row.label}
              </td>
            </tr>
          );
        })}
      </tbody>
    </table>
  );
}

export default function App({
  accentColor = '#0d47a1',
  flashOnChange = false,
}) {
  const [rawInput, setRawInput] = useState('');
  const [debouncedText, setDebouncedText] = useState('');
  const [writeGoodReady, setWriteGoodReady] = useState(isWriteGoodLoaded());
  const [writeGoodError, setWriteGoodError] = useState(hasWriteGoodFailed());
  const [flashToggle, setFlashToggle] = useState(0);

  const copyPicksRef = useRef(null);
  const wasEmptyRef = useRef(true);
  const prevMetricsRef = useRef(null);

  useEffect(() => {
    const timer = setTimeout(() => setDebouncedText(rawInput), 300);
    return () => clearTimeout(timer);
  }, [rawInput]);

  useEffect(() => {
    loadWriteGood()
      .then(() => setWriteGoodReady(true))
      .catch(() => setWriteGoodError(true));
  }, []);

  const gate = useMemo(() => evaluateGate(debouncedText), [debouncedText]);

  const metrics = useMemo(() => {
    if (gate.type !== 'ok') return null;
    return computeMetrics(debouncedText);
  }, [debouncedText, gate.type]);

  useEffect(() => {
    const isEmpty = debouncedText.trim() === '';
    if (isEmpty) {
      wasEmptyRef.current = true;
      copyPicksRef.current = null;
      return;
    }

    if (wasEmptyRef.current && metrics) {
      wasEmptyRef.current = false;
      copyPicksRef.current = rollCopyPicks(metrics);
    }
  }, [debouncedText, metrics]);

  useEffect(() => {
    if (!flashOnChange || !metrics || !prevMetricsRef.current) {
      prevMetricsRef.current = metrics;
      return;
    }
    const prev = prevMetricsRef.current;
    if (
      prev.flesch !== metrics.flesch ||
      prev.cli !== metrics.cli ||
      prev.dale !== metrics.dale ||
      prev.difficultCount !== metrics.difficultCount
    ) {
      setFlashToggle((n) => n + 1);
    }
    prevMetricsRef.current = metrics;
  }, [metrics, flashOnChange]);

  const styleHits = useMemo(() => {
    if (gate.type !== 'ok' || !writeGoodReady) return [];
    return runWriteGood(debouncedText).map((hit) => ({
      ...hit,
      category: categorizeStyleHit(hit.reason),
    }));
  }, [debouncedText, gate.type, writeGoodReady]);

  const skipHighlight = debouncedText.length > 20000;

  const syllableSegments = useMemo(() => {
    if (skipHighlight || gate.type !== 'ok') return null;
    return tokenizeWithGaps(debouncedText).map((seg) => {
      if (seg.type === 'gap') return seg;
      const count = syllableClass(rs.syllableCount(seg.text));
      return { ...seg, syllables: count };
    });
  }, [debouncedText, gate.type, skipHighlight]);

  const hardWordSegments = useMemo(() => {
    if (skipHighlight || gate.type !== 'ok' || !metrics) return null;
    return tokenizeWithGaps(debouncedText).map((seg) => {
      if (seg.type === 'gap') return seg;
      const hard = metrics.difficultLookup.has(seg.text.toLowerCase());
      return { ...seg, hard };
    });
  }, [debouncedText, gate.type, metrics, skipHighlight]);

  const styleRuns = useMemo(() => {
    if (
      skipHighlight ||
      gate.type !== 'ok' ||
      !metrics ||
      styleHits.length === 0
    ) {
      return null;
    }
    const positions = findDifficultWordPositions(
      debouncedText,
      metrics.difficultLookup,
    );
    const categories = buildCharOverlay(debouncedText, positions, styleHits);
    return mergeCharRuns(debouncedText, categories).filter((run) => run.category);
  }, [debouncedText, gate.type, metrics, styleHits, skipHighlight]);

  const chips = useMemo(() => {
    if (!metrics || metrics.difficultCount === 0) return [];
    return getDifficultWordChips(debouncedText, metrics.difficultWords);
  }, [debouncedText, metrics]);

  const copy = copyPicksRef.current;

  const sectionGapFirst = { paddingTop: '1.6rem' };
  const sectionGap = { paddingTop: '2.8rem' };

  return (
    <div
      style={{
        fontFamily: FONT,
        fontSize: '1.05rem',
        lineHeight: 1.5,
        color: '#212121',
        maxWidth: '48rem',
        margin: '0 auto',
        padding: '0 1rem 5rem',
        minHeight: '100vh',
      }}
    >
      <h1
        style={{
          fontSize: '1.05rem',
          fontWeight: 700,
          margin: '2rem 0 1.2rem',
          color: '#212121',
        }}
      >
        Text Readability
      </h1>

      <textarea
        value={rawInput}
        onChange={(e) => setRawInput(e.target.value)}
        placeholder="Paste your text here…"
        spellCheck={false}
        style={{
          width: '100%',
          minHeight: '220px',
          resize: 'vertical',
          display: 'block',
          background: '#f5f7ff',
          border: '1px solid #898ea4',
          borderRadius: '5px',
          padding: '0.75rem 0.9rem',
          font: 'inherit',
          fontSize: '1rem',
          lineHeight: 1.55,
          color: '#212121',
        }}
      />

      {gate.type === 'non-english' && (
        <div
          style={{
            marginTop: '1.6rem',
            background: '#fff6f5',
            border: '1px solid #e6b9b4',
            borderLeft: '4px solid #9a2b2b',
            borderRadius: '5px',
            padding: '0.85rem 1rem',
            display: 'flex',
            gap: '0.65rem',
            alignItems: 'flex-start',
          }}
        >
          <span style={{ fontWeight: 700, color: '#9a2b2b' }}>!</span>
          <span style={{ color: '#7a2222', fontSize: '0.9rem' }}>
            This text doesn&apos;t look like English. Readability scores are calculated for
            English text only. Paste English text to see the metrics.
          </span>
        </div>
      )}

      {gate.type === 'too-short' && (
        <div
          style={{
            marginTop: '1.6rem',
            background: '#f5f5f5',
            border: '1px solid #d9d9d9',
            borderRadius: '5px',
            padding: '0.85rem 1rem',
            display: 'flex',
            gap: '0.65rem',
            alignItems: 'flex-start',
          }}
        >
          <span style={{ fontWeight: 700, color: '#555' }}>i</span>
          <span style={{ color: '#3a3a3a', fontSize: '0.9rem' }}>
            A little more text, please. Readability formulas need at least 12 words to say
            anything meaningful, so add about {12 - gate.wordCount} more.
          </span>
        </div>
      )}

      {gate.type === 'ok' && metrics && copy && (
        <>
          <section style={sectionGapFirst}>
            <h2 style={{ fontSize: '1.05rem', fontWeight: 700, margin: '0 0 0.8rem' }}>
              Overall reading level
            </h2>
            <p
              style={{
                fontWeight: 700,
                fontSize: '1.25rem',
                color: '#212121',
                margin: '0 0 0.8rem',
              }}
            >
              {metrics.textStandard}
            </p>
            <p style={{ color: '#3a3a3a', fontSize: '1rem', lineHeight: 1.6, margin: 0 }}>
              {copy.textStandardIntro}
            </p>
          </section>

          <section style={sectionGap}>
            <h2 style={{ fontSize: '1.05rem', fontWeight: 700, margin: '0 0 0.8rem' }}>
              Flesch Reading Ease
            </h2>
            {syllableSegments && (
              <>
                <Legend
                  items={[
                    { label: '2 syllables', color: SYLLABLE_COLORS[2] },
                    { label: '3 syllables', color: SYLLABLE_COLORS[3] },
                    { label: '4+ syllables', color: SYLLABLE_COLORS[4] },
                  ]}
                />
                <InTextBox>
                  {syllableSegments.map((seg, i) =>
                    seg.type === 'gap' ? (
                      <SegmentSpan key={i} text={seg.text} />
                    ) : (
                      <SegmentSpan
                        key={i}
                        text={seg.text}
                        background={
                          seg.syllables >= 2
                            ? SYLLABLE_COLORS[seg.syllables] ?? SYLLABLE_COLORS[4]
                            : undefined
                        }
                      />
                    ),
                  )}
                </InTextBox>
              </>
            )}
            <p
              style={{
                color: '#3a3a3a',
                fontSize: '1rem',
                lineHeight: 1.6,
                margin: syllableSegments ? '0.9rem 0 0.8rem' : '0 0 0.8rem',
              }}
            >
              {copy.freIntro}
            </p>
            <p style={{ color: '#212121', margin: '0 0 0.9rem' }}>
              Your score is{' '}
              <FlashValue
                value={formatScore(metrics.flesch)}
                flashOnChange={flashOnChange}
                flashToggle={flashToggle}
              />
              , rated {metrics.fleschBand.label.toLowerCase()}. {copy.freReader}
            </p>
            <ScoreTable
              rows={FRE_ROWS}
              activeIndex={metrics.fleschBand.index}
              columns={['Score', 'Difficulty']}
            />
          </section>

          <section style={sectionGap}>
            <h2 style={{ fontSize: '1.05rem', fontWeight: 700, margin: '0 0 0.8rem' }}>
              Coleman–Liau Index
            </h2>
            <p
              style={{
                color: '#3a3a3a',
                fontSize: '1rem',
                lineHeight: 1.6,
                margin: '0 0 0.8rem',
              }}
            >
              {copy.cliIntro}
            </p>
            <p style={{ color: '#212121', margin: 0 }}>
              The Coleman–Liau Index puts this text at about grade{' '}
              <FlashValue
                value={formatScore(metrics.cli)}
                flashOnChange={flashOnChange}
                flashToggle={flashToggle}
              />
              . {copy.cliReader}
            </p>
          </section>

          <section style={sectionGap}>
            <h2 style={{ fontSize: '1.05rem', fontWeight: 700, margin: '0 0 0.8rem' }}>
              Dale–Chall Readability
            </h2>
            <p
              style={{
                color: '#3a3a3a',
                fontSize: '1rem',
                lineHeight: 1.6,
                margin: '0 0 0.8rem',
              }}
            >
              {copy.daleIntro}
            </p>
            <p style={{ color: '#212121', margin: '0 0 0.9rem' }}>
              Your score is{' '}
              <FlashValue
                value={formatScore(metrics.dale)}
                flashOnChange={flashOnChange}
                flashToggle={flashToggle}
              />
              , a {metrics.daleBand.label.toLowerCase()} reading level. {copy.daleReader}
            </p>
            <ScoreTable
              rows={DALE_ROWS}
              activeIndex={metrics.daleBand.index}
              columns={['Score', 'Reading level']}
            />
          </section>

          <section style={sectionGap}>
            <h2 style={{ fontSize: '1.05rem', fontWeight: 700, margin: '0 0 0.8rem' }}>
              Difficult words
            </h2>
            {metrics.difficultCount >= 1 && hardWordSegments && (
              <>
                <Legend items={[{ label: 'Hard word', color: '#d8efdb' }]} />
                <InTextBox>
                  {hardWordSegments.map((seg, i) =>
                    seg.type === 'gap' ? (
                      <SegmentSpan key={i} text={seg.text} />
                    ) : (
                      <SegmentSpan
                        key={i}
                        text={seg.text}
                        background={seg.hard ? '#d8efdb' : undefined}
                      />
                    ),
                  )}
                </InTextBox>
              </>
            )}
            <p
              style={{
                color: '#3a3a3a',
                fontSize: '1rem',
                lineHeight: 1.6,
                margin:
                  metrics.difficultCount >= 1 && hardWordSegments
                    ? '0.9rem 0 0.8rem'
                    : '0 0 0.8rem',
              }}
            >
              {metrics.difficultCount > 0
                ? `${metrics.difficultWords.length} distinct words below account for ${metrics.difficultCount} of your ${metrics.lexicon} words (about ${Math.round((metrics.difficultCount / metrics.lexicon) * 100)}%). These are the longer, less familiar words the formulas count against you, so swapping them for simpler ones is the quickest way to lift every score above.`
                : 'Nothing stands out. Your text is built almost entirely from short, familiar words, which is exactly what keeps the scores easy.'}
            </p>
            {chips.length > 0 && (
              <div style={{ display: 'flex', flexWrap: 'wrap', gap: '0.5rem' }}>
                {chips.map((chip) => (
                  <span
                    key={chip.word}
                    style={{
                      padding: '0.4rem 0.8rem',
                      background: '#f5f5f5',
                      border: '1px solid #d9d9d9',
                      borderRadius: '999px',
                      fontSize: '0.95rem',
                      display: 'inline-flex',
                      alignItems: 'center',
                      gap: '0.45rem',
                    }}
                  >
                    {chip.word}
                    {chip.count > 1 && (
                      <span
                        style={{
                          background: '#e0e0e0',
                          borderRadius: '999px',
                          fontSize: '0.72rem',
                          fontWeight: 700,
                          color: '#555',
                          padding: '0.1rem 0.4rem',
                        }}
                      >
                        ×{chip.count}
                      </span>
                    )}
                  </span>
                ))}
              </div>
            )}
          </section>

          <section style={sectionGap}>
            <h2 style={{ fontSize: '1.05rem', fontWeight: 700, margin: '0 0 0.8rem' }}>
              Style check
            </h2>

            {!writeGoodReady && !writeGoodError && (
              <p style={{ color: '#898ea4', fontSize: '0.95rem', margin: '0 0 0.8rem' }}>
                Loading style check…
              </p>
            )}

            {writeGoodError && (
              <p style={{ color: '#898ea4', fontSize: '0.95rem', margin: '0 0 0.8rem' }}>
                Style check couldn&apos;t load.
              </p>
            )}

            {writeGoodReady && styleRuns && (
              <>
                <Legend items={STYLE_LEGEND} />
                <InTextBox>
                  {styleRuns.map((run, i) => (
                    <SegmentSpan
                      key={i}
                      text={run.text}
                      background={STYLE_COLORS[run.category] ?? STYLE_COLORS.Style}
                    />
                  ))}
                </InTextBox>
              </>
            )}

            {writeGoodReady && (
              <>
                <p
                  style={{
                    color: '#3a3a3a',
                    fontSize: '1rem',
                    lineHeight: 1.6,
                    margin:
                      styleRuns ? '0.9rem 0 0.8rem' : '0 0 0.8rem',
                  }}
                >
                  {styleHits.length === 0
                    ? 'Clean. Nothing flagged for passive voice, filler, or hedging words.'
                    : `${styleHits.length} phrase${styleHits.length === 1 ? '' : 's'} ${styleHits.length === 1 ? 'is' : 'are'} worth a second look. Passive voice, filler and hedging words make writing feel heavier than it needs to, so tightening these reads more directly.`}
                </p>

                {styleHits.length > 0 && (
                  <div>
                    {styleHits.map((hit, i) => (
                      <div
                        key={`${hit.index}-${hit.offset}-${i}`}
                        style={{
                          display: 'flex',
                          gap: '0.9rem',
                          padding: '0.7rem 0',
                          borderBottom: '1px solid #eee',
                        }}
                      >
                        <span
                          style={{
                            minWidth: '6.5rem',
                            fontSize: '0.78rem',
                            fontWeight: 700,
                            letterSpacing: '0.02em',
                            color: '#555',
                            flexShrink: 0,
                          }}
                        >
                          {hit.category}
                        </span>
                        <span style={{ color: '#212121', fontSize: '1rem' }}>{hit.reason}</span>
                      </div>
                    ))}
                  </div>
                )}
              </>
            )}
          </section>
        </>
      )}
    </div>
  );
}
